### ISSUE TITLE
App Background Animation

### ISSUE THREAD

**Issue by Fabio-Ricci** [ErickSaito/MC855#10]
- [x] Define and implement app splash screen background image and animations
- [x] Define and implement Main Screen background image and animations

**Comment by paulopacitti** [comment]
- #13: The animation approach that we tried to implement did not work. Since we spend a lot of time on this, we decided to priotize other tasks for Sprint 2 - 
- #14: the splashscreen was implemented following the Android and iOS app development recommendations: the logo with a solid color background
